config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'candidates#index'
  resources :candidates
  post '/candidates/:id/voteoo', to: 'candidates#jeslythecool'
  get '/snake', to:'candidates#snake'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, :length => { :minimum => 3, :maximum =>10}
  validates :title, :length => { :maximum =>40}, allow_blank: false
  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  validates :email, uniqueness: true
  validates :username, uniqueness: true


  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email])
  end

  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction



  # GET /candidates
  # GET /candidates.json


  def index
  #@candidates = Candidate.all
  #@candidates = Candidate.order("#{sort_column} #{sort_direction}")
  #raise params.inspect
  @candidates = Candidate.left_joins(:votes).group(:id).order("count('votes.candidate_id') #{params[:sort_order]}")
  end
#
  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end
#Hausaufgabe 1 24.06.2018
  def jeslythecool
    selected_candidate.votes.create
    respond_to do |format|
    format.html { redirect_to candidates_url, notice: "You voted successfully for #{selected_candidate.name}"  }
    format.json { head :no_content }
    end
  end
  def snake
    render:showsnake
  end

  def selected_candidate
    @can = Candidate.find params[:id]
  end
  # POST /candidates
  # POST /candidates.json
  def sortable_columns
    ["name", "title"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence} </h2>
      <ul>#{messages} </ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>
<tr>Welcome <%= current_user.name%></tr>
<h1>Candidates</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Votes</th>
      <th>Action1</th>
      <th>Action2</th>
      <th>Action3</th>
      <th><%= link_to 'Votes Count', "/candidates?sort_order=desc" %></th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td> <p style="color:#FF0000";><%= candidate.name %> </p></td>
        <td><%= candidate.title %></td>
        <td><%= button_to 'vote', "/candidates/#{candidate.id}/voteoo", method: :post %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= candidate.votes.count %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/showsnake.html.erb
<p id="demo"></p>
<script>

var xorientation = 10
var yorientation = 10
var zorientation = 80
var borientation = 80
function myFunction(){
  document.getElementById("hiddenX").innerHTML = text;
//document.getElementById('hiddenX').innerHTML = ' ';
}

var text = "";
var i;
for (i = 0; i < 5; i++) {

  function moveXhorizontal(){

requestAnimationFrame(moveXhorizontal);

  //*document.getElementById('hiddenX').style.padding="0px 0px 0px "+xorientation+'px';
    if (xorientation<90) {

      document.getElementById('hiddenX').style.padding="0px 0px 0px "+xorientation+'px';
      xorientation=xorientation+10;

    }  else {
      if (yorientation<90) {


        document.getElementById('hiddenX').style.padding=yorientation+"px 0px 0px 80px ";
        yorientation=yorientation+10;
  //*document.getElementById('hiddenX').style.padding=xorientation+'px';
//*xorientation=xorientation+2;
      }  else {
        if (zorientation<90 && zorientation>10) {
          document.getElementById('hiddenX').style.padding="80px 0px 0px "+zorientation+'px';
          zorientation=zorientation-10;

        }  else {
          if(borientation<90 && borientation>6) {
            document.getElementById('hiddenX').style.padding=borientation+"px 0px 0px 0px";
            borientation=borientation-10;

            }  else {
              xorientation = 4
              yorientation = 8
              zorientation = 75
              borientation = 75



}
}
}
}
}
}
document.getElementById("demo").innerHTML = text;
</script>



<div style="height:100px; width:100px; background-color:red" >
<div id="hiddenX" style="left: 10px" onclick="requestAnimationFrame(moveXhorizontal)">xxx</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EomFinal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>